language: python

python:
  - "2.7"

cache: pip

install:
  - pip install -r requirements.txt
  - pip install codecov  
  - pip install pytest-cov


# command to run tests
script: 
  - ./INSTALL.sh
  - sh tests/test_pipeline_linux.sh
  - py.test --cov=./

after_success:
  - codecov